project:
  type: book

book:
  title: "Statistics for Business and Economics"
  author: 
  - name: "Mohammad Saifuddin"
    affiliation: "Assistant Professor, Department of Mathematics and  Statistics, BUBT"

  
  date: today
  cover-image: "cover.jpg"

  chapters:
    - index.qmd
    - intro.qmd
    - descriptive_graph_tab.qmd
    - descriptive_numer_measures.qmd
    - Probability.qmd
    - randomvariable_and_discrete probability dist.qmd
    - continuous_r.v.qmd
    - Further_topics_on_rv.qmd
    - sampling_and_sampling_distributions.qmd
    - estimation.qmd
    - hypothesis_test.qmd
    - Correlation.qmd
    #- Multiple_linear.qmd
    - summary.qmd
    - references.qmd

  downloads: [pdf, epub]
  sidebar:
    pinned: true
    tools:
      - icon: save
        menu:
          - text: ""
            url:  "#"
          - text: ""
            url:  "#"
          - text: ""
            url:  "#"
            
  repo-url: https://github.com/Saifuddin86/stat_for_businessNeconomics   
  search: 
    location: sidebar
    type: textbox    

execute: 
  echo: true
  warning: false

bibliography: references.bib


format:
  html:
    grid:
      margin-width: 300px
      body-width: 900px
      sidebar-width: 300px
      gutter-width: 1.5rem
    theme: cosmo
    code-fold: true
  pdf:
    documentclass: scrreprt
    geometry:
      - top=20mm
      - bottom=25mm
      - left=25mm
      - right=25mm
      - heightrounded
  
css: styles.css
editor: visual